---
language: node_js
node_js:
  - node
  - lts/*

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm run build
  - npx react-scripts test --coverage
  - npx tsc
